version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: exercise-app-image
    container_name: exercise-app-container
    volumes:
      - ./:/var/www
    ports:
     - 8000:8000
    networks:
      - exercise_app_network

  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - 3307:3306
    networks:
      - exercise_app_network

networks:
  exercise_app_network:
    driver: bridge
